apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: capten-clusterbinding
subjects:
- kind: ServiceAccount
  name: tekton-triggers-capten
  namespace: capten-build
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-clusterrole
